In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
hh_df = pd.read_csv('home_ac/processed_hhdata_86_2.csv')
# print(hh_df.shape)
# hh_df.head(15)
hh_df.drop_duplicates(subset ="localhour", keep = False, inplace = True)
print(hh_df.shape)

(8651, 10)

In [3]:
hh_df['hour_index']=0
#hh_df.iloc[-50]

In [4]:
used = ['localhour', 'use', 'temperature', 'cloud_cover','GH', 'is_weekday','month','hour','AC','DC','hour_index']
datarow= []

In [5]:

hour_index=0#hour index
hour_value=0
missing_count=0
start_time= pd.to_datetime(hh_df['localhour'].iloc[0][:-3])
for index, row in hh_df.iterrows():
    row.localhour=row.localhour[:-3]
    #print(row.localhour)
    difference=(pd.to_datetime(row.localhour)-pd.to_datetime(hh_df['localhour'].iloc[0][:-3])).total_seconds()/3600
    #print("index is difference",difference)
    
    if difference!=hour_index:
        gap = difference-hour_index
        missing_count += gap
        #fill in the missing hours
        for i in range(int(gap)):
            print("\n---------------------------------------")
            print("missing data for hour index:",hour_index+i)
            #row.hour=(hour_index+i)%24
            temprow=None
            #print("this is lastrow",lastrow)
            temprow=lastrow
            #print("this is temprow",temprow)
            temprow.hour_index=hour_index+i
            #print("this is hour of lastrow",lastrow.hour)
            #temprow.hour = (hour_index+i)%24
            current_time = start_time+pd.Timedelta(hour_index+i,unit='h')
            temprow.localhour = current_time
            temprow.hour = current_time.hour
            temprow.month = current_time.month
            temprow.is_weekday = int(datetime.strptime(str(current_time), "%Y-%m-%d %H:%M:%S").weekday() < 5)
            print("The inserted row is \n",temprow)
            #datarow.append(row[used])
            datarow.append(temprow[used])
            temprow=None
            #hour=None
            #print(datarow)
        hour_index = difference
    hour_index +=1
    row.hour_index=difference
    #hour_value = row.hour
    #print(row[used])
    #print("reach here")
    lastrow = row[used]
    datarow.append(row[used])
print("total missing hours",missing_count)



    
       
#------------------------------------------testing----------------------------
# hour_index=0 #hour index
# missing_count=0
# for index, row in hh_df.iterrows():
#     #print(row.localhour)
#     #row.month = float(pd.to_datetime(row.localhour[:-3]).month)
#     #row.day = float(pd.to_datetime(row.localhour[:-3]).day)
#     #data_hour = float(pd.to_datetime(row.localhour).hour-6)%24
#     data_hour = float(pd.to_datetime(row.localhour[:-3]).hour)
#     #print(data_hour)
#     if data_hour != hour_index%24:
#         print("we are missing hours for",row.localhour)
#         missing_count += 1
#         hour_index +=1
#     hour_index += 1
# print("In total missing hours", missing_count)

# for index, row in hh_df.iterrows():
#     #row.month = float(pd.to_datetime(row.localhour[:-3]).month)
#     #row.day = float(pd.to_datetime(row.localhour[:-3]).day)
#     print("------------")
#     print(row.localhour)
#     print(float(pd.to_datetime(row.localhour).hour-6)%24)
#     print(float(pd.to_datetime(row.localhour[:-3]).hour))
# #     print(pd.to_datetime(row.localhour))
# #     print(pd.to_datetime(row.localhour).tz_localize('UTC'))
# #     print(pd.to_datetime(row.localhour).tz_localize('UTC').tz_convert('US/Central'))
# #     print(pd.to_datetime(row.localhour[:-3]).tz_localize('US/Central'))
# #     print(pd.to_datetime(row.localhour)-pd.Timedelta('06:00:00'))

---------------------------------------
missing data for hour index: 1730
The inserted row is
 localhour      2016-03-13 02:00:00
use                       0.562467
temperature                  57.88
cloud_cover                      0
GH                        -2.38039
is_weekday                       0
month                            3
hour                             2
AC                               0
hour_index                    1730
Name: 1729, dtype: object

---------------------------------------
missing data for hour index: 1992.0
The inserted row is
 localhour      2016-03-24 00:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                             0
AC                               0
hour_index                    1992
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 1993.0
The inserted row is
 localhour      2016-03-24 01:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                             1
AC                               0
hour_index                    1993
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 1994.0
The inserted row is
 localhour      2016-03-24 02:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                             2
AC                               0
hour_index                    1994
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 1995.0
The inserted row is
 localhour      2016-03-24 03:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                             3
AC                               0
hour_index                    1995
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 1996.0
The inserted row is
 localhour      2016-03-24 04:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                             4
AC                               0
hour_index                    1996
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 1997.0
The inserted row is
 localhour      2016-03-24 05:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                             5
AC                               0
hour_index                    1997
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 1998.0
The inserted row is
 localhour      2016-03-24 06:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                             6
AC                               0
hour_index                    1998
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 1999.0
The inserted row is
 localhour      2016-03-24 07:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                             7
AC                               0
hour_index                    1999
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2000.0
The inserted row is
 localhour      2016-03-24 08:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                             8
AC                               0
hour_index                    2000
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2001.0
The inserted row is
 localhour      2016-03-24 09:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                             9
AC                               0
hour_index                    2001
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2002.0
The inserted row is
 localhour      2016-03-24 10:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            10
AC                               0
hour_index                    2002
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2003.0
The inserted row is
 localhour      2016-03-24 11:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            11
AC                               0
hour_index                    2003
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2004.0
The inserted row is
 localhour      2016-03-24 12:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            12
AC                               0
hour_index                    2004
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2005.0
The inserted row is
 localhour      2016-03-24 13:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            13
AC                               0
hour_index                    2005
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2006.0
The inserted row is
 localhour      2016-03-24 14:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            14
AC                               0
hour_index                    2006
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2007.0
The inserted row is
 localhour      2016-03-24 15:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            15
AC                               0
hour_index                    2007
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2008.0
The inserted row is
 localhour      2016-03-24 16:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            16
AC                               0
hour_index                    2008
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2009.0
The inserted row is
 localhour      2016-03-24 17:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            17
AC                               0
hour_index                    2009
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2010.0
The inserted row is
 localhour      2016-03-24 18:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            18
AC                               0
hour_index                    2010
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2011.0
The inserted row is
 localhour      2016-03-24 19:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            19
AC                               0
hour_index                    2011
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2012.0
The inserted row is
 localhour      2016-03-24 20:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            20
AC                               0
hour_index                    2012
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2013.0
The inserted row is
 localhour      2016-03-24 21:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            21
AC                               0
hour_index                    2013
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2014.0
The inserted row is
 localhour      2016-03-24 22:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            22
AC                               0
hour_index                    2014
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2015.0
The inserted row is
 localhour      2016-03-24 23:00:00
use                       0.465617
temperature                  69.18
cloud_cover                   0.99
GH                        -2.71949
is_weekday                       1
month                            3
hour                            23
AC                               0
hour_index                    2015
Name: 1990, dtype: object

---------------------------------------
missing data for hour index: 2040.0
The inserted row is
 localhour      2016-03-26 00:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                             0
AC                               0
hour_index                    2040
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2041.0
The inserted row is
 localhour      2016-03-26 01:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                             1
AC                               0
hour_index                    2041
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2042.0
The inserted row is
 localhour      2016-03-26 02:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                             2
AC                               0
hour_index                    2042
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2043.0
The inserted row is
 localhour      2016-03-26 03:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                             3
AC                               0
hour_index                    2043
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2044.0
The inserted row is
 localhour      2016-03-26 04:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                             4
AC                               0
hour_index                    2044
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2045.0
The inserted row is
 localhour      2016-03-26 05:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                             5
AC                               0
hour_index                    2045
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2046.0
The inserted row is
 localhour      2016-03-26 06:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                             6
AC                               0
hour_index                    2046
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2047.0
The inserted row is
 localhour      2016-03-26 07:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                             7
AC                               0
hour_index                    2047
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2048.0
The inserted row is
 localhour      2016-03-26 08:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                             8
AC                               0
hour_index                    2048
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2049.0
The inserted row is
 localhour      2016-03-26 09:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                             9
AC                               0
hour_index                    2049
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2050.0
The inserted row is
 localhour      2016-03-26 10:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                            10
AC                               0
hour_index                    2050
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2051.0
The inserted row is
 localhour      2016-03-26 11:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                            11
AC                               0
hour_index                    2051
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2052.0
The inserted row is
 localhour      2016-03-26 12:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                            12
AC                               0
hour_index                    2052
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2053.0
The inserted row is
 localhour      2016-03-26 13:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                            13
AC                               0
hour_index                    2053
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2054.0
The inserted row is
 localhour      2016-03-26 14:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                            14
AC                               0
hour_index                    2054
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2055.0
The inserted row is
 localhour      2016-03-26 15:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                            15
AC                               0
hour_index                    2055
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2056.0
The inserted row is
 localhour      2016-03-26 16:00:00
use                       0.279933
temperature                  58.02
cloud_cover                   0.01
GH                        -2.72109
is_weekday                       0
month                            3
hour                            16
AC                               0
hour_index                    2056
Name: 2014, dtype: object

---------------------------------------
missing data for hour index: 2057.0

---------------------------------------
missing data for hour index: 6648.0
The inserted row is
 localhour      2016-10-04 00:00:00
use                       0.978167
temperature                  71.98
cloud_cover                   0.02
GH                        -2.71989
is_weekday                       1
month                           10
hour                             0
AC                               0
hour_index                    6648
Name: 6598, dtype: object

---------------------------------------
missing data for hour index: 6649.0
The inserted row is
 localhour      2016-10-04 01:00:00
use                       0.978167
temperature                  71.98
cloud_cover                   0.02
GH                        -2.71989
is_weekday                       1
month                           10
hour                             1
AC                               0
hour_index                    6649
Name: 6598, dtype: object

---------------------------------------
missing data for hour index: 6650.0
The inserted row is
 localhour      2016-10-04 02:00:00
use                       0.978167
temperature                  71.98
cloud_cover                   0.02
GH                        -2.71989
is_weekday                       1
month                           10
hour                             2
AC                               0
hour_index                    6650
Name: 6598, dtype: object

---------------------------------------
missing data for hour index: 6651.0
The inserted row is
 localhour      2016-10-04 03:00:00
use                       0.978167
temperature                  71.98
cloud_cover                   0.02
GH                        -2.71989
is_weekday                       1
month                           10
hour                             3
AC                               0
hour_index                    6651
Name: 6598, dtype: object

---------------------------------------
missing data for hour index: 6652.0
The inserted row is
 localhour      2016-10-04 04:00:00
use                       0.978167
temperature                  71.98
cloud_cover                   0.02
GH                        -2.71989
is_weekday                       1
month                           10
hour                             4
AC                               0
hour_index                    6652
Name: 6598, dtype: object

---------------------------------------
missing data for hour index: 6866.0
The inserted row is
 localhour      2016-10-13 02:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             2
AC                               0
hour_index                    6866
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6867.0
The inserted row is
 localhour      2016-10-13 03:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             3
AC                               0
hour_index                    6867
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6868.0
The inserted row is
 localhour      2016-10-13 04:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             4
AC                               0
hour_index                    6868
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6869.0
The inserted row is
 localhour      2016-10-13 05:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             5
AC                               0
hour_index                    6869
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6870.0
The inserted row is
 localhour      2016-10-13 06:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             6
AC                               0
hour_index                    6870
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6871.0
The inserted row is
 localhour      2016-10-13 07:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             7
AC                               0
hour_index                    6871
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6872.0
The inserted row is
 localhour      2016-10-13 08:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             8
AC                               0
hour_index                    6872
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6873.0
The inserted row is
 localhour      2016-10-13 09:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             9
AC                               0
hour_index                    6873
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6874.0
The inserted row is
 localhour      2016-10-13 10:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            10
AC                               0
hour_index                    6874
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6875.0
The inserted row is
 localhour      2016-10-13 11:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            11
AC                               0
hour_index                    6875
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6876.0
The inserted row is
 localhour      2016-10-13 12:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            12
AC                               0
hour_index                    6876
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6877.0
The inserted row is
 localhour      2016-10-13 13:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            13
AC                               0
hour_index                    6877
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6878.0
The inserted row is
 localhour      2016-10-13 14:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            14
AC                               0
hour_index                    6878
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6879.0
The inserted row is
 localhour      2016-10-13 15:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            15
AC                               0
hour_index                    6879
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6880.0
The inserted row is
 localhour      2016-10-13 16:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            16
AC                               0
hour_index                    6880
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6881.0
The inserted row is
 localhour      2016-10-13 17:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            17
AC                               0
hour_index                    6881
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6882.0
The inserted row is
 localhour      2016-10-13 18:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            18
AC                               0
hour_index                    6882
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6883.0
The inserted row is
 localhour      2016-10-13 19:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            19
AC                               0
hour_index                    6883
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6884.0
The inserted row is
 localhour      2016-10-13 20:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            20
AC                               0
hour_index                    6884
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6885.0
The inserted row is
 localhour      2016-10-13 21:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            21
AC                               0
hour_index                    6885
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6886.0
The inserted row is
 localhour      2016-10-13 22:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            22
AC                               0
hour_index                    6886
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6887.0
The inserted row is
 localhour      2016-10-13 23:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                            23
AC                               0
hour_index                    6887
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6888.0
The inserted row is
 localhour      2016-10-14 00:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             0
AC                               0
hour_index                    6888
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6889.0
The inserted row is
 localhour      2016-10-14 01:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             1
AC                               0
hour_index                    6889
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6890.0
The inserted row is
 localhour      2016-10-14 02:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             2
AC                               0
hour_index                    6890
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6891.0
The inserted row is
 localhour      2016-10-14 03:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             3
AC                               0
hour_index                    6891
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6892.0
The inserted row is
 localhour      2016-10-14 04:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             4
AC                               0
hour_index                    6892
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6893.0
The inserted row is
 localhour      2016-10-14 05:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             5
AC                               0
hour_index                    6893
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6894.0
The inserted row is
 localhour      2016-10-14 06:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             6
AC                               0
hour_index                    6894
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6895.0
The inserted row is
 localhour      2016-10-14 07:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             7
AC                               0
hour_index                    6895
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6896.0
The inserted row is
 localhour      2016-10-14 08:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             8
AC                               0
hour_index                    6896
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 6897.0
The inserted row is
 localhour      2016-10-14 09:00:00
use                       0.490583
temperature                  79.24
cloud_cover                   0.06
GH                        -2.71989
is_weekday                       1
month                           10
hour                             9
AC                               0
hour_index                    6897
Name: 6811, dtype: object

---------------------------------------
missing data for hour index: 7614.0
The inserted row is
 localhour      2016-11-13 06:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                             6
AC                               0
hour_index                    7614
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7615.0
The inserted row is
 localhour      2016-11-13 07:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                             7
AC                               0
hour_index                    7615
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7616.0
The inserted row is
 localhour      2016-11-13 08:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                             8
AC                               0
hour_index                    7616
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7617.0
The inserted row is
 localhour      2016-11-13 09:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                             9
AC                               0
hour_index                    7617
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7618.0
The inserted row is
 localhour      2016-11-13 10:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            10
AC                               0
hour_index                    7618
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7619.0
The inserted row is
 localhour      2016-11-13 11:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            11
AC                               0
hour_index                    7619
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7620.0
The inserted row is
 localhour      2016-11-13 12:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            12
AC                               0
hour_index                    7620
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7621.0
The inserted row is
 localhour      2016-11-13 13:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            13
AC                               0
hour_index                    7621
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7622.0
The inserted row is
 localhour      2016-11-13 14:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            14
AC                               0
hour_index                    7622
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7623.0
The inserted row is
 localhour      2016-11-13 15:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            15
AC                               0
hour_index                    7623
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7624.0
The inserted row is
 localhour      2016-11-13 16:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            16
AC                               0
hour_index                    7624
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7625.0
The inserted row is
 localhour      2016-11-13 17:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            17
AC                               0
hour_index                    7625
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7626.0
The inserted row is
 localhour      2016-11-13 18:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            18
AC                               0
hour_index                    7626
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7627.0
The inserted row is
 localhour      2016-11-13 19:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            19
AC                               0
hour_index                    7627
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7628.0
The inserted row is
 localhour      2016-11-13 20:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            20
AC                               0
hour_index                    7628
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7629.0
The inserted row is
 localhour      2016-11-13 21:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            21
AC                               0
hour_index                    7629
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7630.0
The inserted row is
 localhour      2016-11-13 22:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            22
AC                               0
hour_index                    7630
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7631.0
The inserted row is
 localhour      2016-11-13 23:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       0
month                           11
hour                            23
AC                               0
hour_index                    7631
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7632.0
The inserted row is
 localhour      2016-11-14 00:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       1
month                           11
hour                             0
AC                               0
hour_index                    7632
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7633.0
The inserted row is
 localhour      2016-11-14 01:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       1
month                           11
hour                             1
AC                               0
hour_index                    7633
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7634.0
The inserted row is
 localhour      2016-11-14 02:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       1
month                           11
hour                             2
AC                               0
hour_index                    7634
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7635.0
The inserted row is
 localhour      2016-11-14 03:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       1
month                           11
hour                             3
AC                               0
hour_index                    7635
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7636.0
The inserted row is
 localhour      2016-11-14 04:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       1
month                           11
hour                             4
AC                               0
hour_index                    7636
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 7637.0
The inserted row is
 localhour      2016-11-14 05:00:00
use                         0.2969
temperature                  60.77
cloud_cover                   0.07
GH                        -2.72375
is_weekday                       1
month                           11
hour                             5
AC                               0
hour_index                    7637
Name: 7527, dtype: object

---------------------------------------
missing data for hour index: 8742.0
The inserted row is
 localhour      2016-12-30 06:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                             6
AC                               0
hour_index                    8742
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8743.0
The inserted row is
 localhour      2016-12-30 07:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                             7
AC                               0
hour_index                    8743
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8744.0
The inserted row is
 localhour      2016-12-30 08:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                             8
AC                               0
hour_index                    8744
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8745.0
The inserted row is
 localhour      2016-12-30 09:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                             9
AC                               0
hour_index                    8745
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8746.0
The inserted row is
 localhour      2016-12-30 10:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            10
AC                               0
hour_index                    8746
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8747.0
The inserted row is
 localhour      2016-12-30 11:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            11
AC                               0
hour_index                    8747
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8748.0
The inserted row is
 localhour      2016-12-30 12:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            12
AC                               0
hour_index                    8748
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8749.0
The inserted row is
 localhour      2016-12-30 13:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            13
AC                               0
hour_index                    8749
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8750.0
The inserted row is
 localhour      2016-12-30 14:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            14
AC                               0
hour_index                    8750
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8751.0
The inserted row is
 localhour      2016-12-30 15:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            15
AC                               0
hour_index                    8751
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8752.0
The inserted row is
 localhour      2016-12-30 16:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            16
AC                               0
hour_index                    8752
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8753.0
The inserted row is
 localhour      2016-12-30 17:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            17
AC                               0
hour_index                    8753
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8754.0
The inserted row is
 localhour      2016-12-30 18:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            18
AC                               0
hour_index                    8754
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8755.0
The inserted row is
 localhour      2016-12-30 19:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            19
AC                               0
hour_index                    8755
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8756.0
The inserted row is
 localhour      2016-12-30 20:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            20
AC                               0
hour_index                    8756
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8757.0
The inserted row is
 localhour      2016-12-30 21:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            21
AC                               0
hour_index                    8757
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8758.0
The inserted row is
 localhour      2016-12-30 22:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            22
AC                               0
hour_index                    8758
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8759.0
The inserted row is
 localhour      2016-12-30 23:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       1
month                           12
hour                            23
AC                               0
hour_index                    8759
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8760.0
The inserted row is
 localhour      2016-12-31 00:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       0
month                           12
hour                             0
AC                               0
hour_index                    8760
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8761.0
The inserted row is
 localhour      2016-12-31 01:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       0
month                           12
hour                             1
AC                               0
hour_index                    8761
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8762.0
The inserted row is
 localhour      2016-12-31 02:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       0
month                           12
hour                             2
AC                               0
hour_index                    8762
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8763.0
The inserted row is
 localhour      2016-12-31 03:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       0
month                           12
hour                             3
AC                               0
hour_index                    8763
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8764.0
The inserted row is
 localhour      2016-12-31 04:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       0
month                           12
hour                             4
AC                               0
hour_index                    8764
Name: 8679, dtype: object

---------------------------------------
missing data for hour index: 8765.0
The inserted row is
 localhour      2016-12-31 05:00:00
use                        0.25915
temperature                  47.35
cloud_cover                      0
GH                       -0.454468
is_weekday                       0
month                           12
hour                             5
AC                               0
hour_index                    8765
Name: 8679, dtype: object
total missing hours 134.0

In [6]:
df = pd.DataFrame(data=datarow, columns=used)
print(df.head())
df.to_csv('datanew/afterfix6.csv')

             localhour       use  temperature  cloud_cover       GH  \
0  2016-01-01 00:00:00  0.500100        47.22         0.96 -1.70260
1  2016-01-01 01:00:00  0.544467        46.50         1.00 -1.65152
2  2016-01-01 02:00:00  0.501350        46.04         1.00 -1.70257
3  2016-01-01 03:00:00  0.464817        45.34         1.00 -1.91251
4  2016-01-01 04:00:00  0.473133        44.49         1.00 -2.39497

   is_weekday  month  hour   AC  hour_index
0           1      1     0  0.0         0.0
1           1      1     1  0.0         1.0
2           1      1     2  0.0         2.0
3           1      1     3  0.0         3.0
4           1      1     4  0.0         4.0